# Generated by Django 4.2.4 on 2023-09-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Employee_Code', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Employee_Gender', models.CharField(max_length=100)),
                ('Employee_Role', models.CharField(max_length=100)),
                ('Employee_Doj', models.DateField(max_length=100)),
                ('Employee_Bsalary', models.IntegerField(max_length=100)),
                ('Employee_Fname', models.CharField(max_length=100)),
                ('Employee_Dob', models.DateField(max_length=100)),
                ('Employee_Fphone', models.CharField(max_length=100)),
                ('Employee_Adhaar', models.IntegerField(max_length=100)),
                ('Employee_Address', models.CharField(max_length=100)),
                ('Employee_Phone', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary_slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('Employee_Code', models.IntegerField()),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Employee_Bsalary', models.IntegerField()),
                ('No_Of_Days_Worked', models.IntegerField()),
                ('Salary_of_Month', models.IntegerField()),
                ('Da', models.IntegerField()),
                ('Hra', models.IntegerField()),
                ('Conveyance', models.IntegerField()),
                ('Gross', models.IntegerField()),
                ('Deduction', models.IntegerField()),
                ('Net', models.IntegerField()),
            ],
        ),
    ]
