# Generated by Django 4.2.4 on 2023-09-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_home_delete_admins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
