# Generated by Django 4.2.4 on 2023-09-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Code', models.IntegerField()),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
