# Generated by Django 4.2.4 on 2023-09-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_employees_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='Employee_Name',
        ),
        migrations.AddField(
            model_name='leave',
            name='Employee_Code',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Employee_Code',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
