# Generated by Django 4.2.4 on 2023-09-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_leave_employee_name_leave_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Password',
            field=models.CharField(default=100, max_length=30),
        ),
        migrations.AddField(
            model_name='employees',
            name='Username',
            field=models.CharField(default='hello', max_length=30),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Employee_Code',
            field=models.AutoField(auto_created=True, default=1011, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Employee_Code',
            field=models.IntegerField(max_length=100),
        ),
    ]
