# Generated by Django 4.2.4 on 2023-09-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_employees_password_employees_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Employee_Code',
            field=models.AutoField(auto_created=True, default=101, primary_key=True, serialize=False),
        ),
    ]
