# Generated by Django 4.2.4 on 2023-09-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_employees_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Username',
            field=models.CharField(max_length=30),
        ),
    ]
