# Generated by Django 4.2.4 on 2023-09-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_employees_password_alter_employees_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Employee_Code',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
