# Generated by Django 4.2.4 on 2023-09-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_employees_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Username',
        ),
        migrations.AddField(
            model_name='admins',
            name='code',
            field=models.IntegerField(default=100, max_length=10),
        ),
    ]
