# Generated by Django 4.2.4 on 2023-09-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_employees_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='code',
            field=models.IntegerField(max_length=10),
        ),
    ]
