# Generated by Django 4.2.4 on 2023-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_admins_id_alter_admins_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
