# Generated by Django 4.2.4 on 2023-09-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_admins_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='code',
            field=models.AutoField(default=103, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Employee_Code',
            field=models.AutoField(auto_created=True, default=103, primary_key=True, serialize=False),
        ),
    ]
