# Generated by Django 4.2.4 on 2023-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_admins_code_alter_employees_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Employee_Code',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
